Fear/challenge 03 loops conditionals
AGUACATE2304/JavaScript-foundations-challenge-1 pull request #3
Opened 2023-10-31 18:01 UTC by AGUACATE2304

2023-10-31 18:04 UTC, AGUACATE2304 commented
All the code is formated, at the end of the script line, by the autoSave, I did the  "npx prettier . --write" and didn't refactorized anything

2023-11-05 16:13 UTC, tictools requested changes

2023-11-05 16:13 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +if (randomNumber % 2 === 0) {
⚠️ FIX: Change the variable to test it works for different cases. Print result.

2023-11-05 16:13 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let number = 10; 40 >= number; number++) {
```suggestion
for (let number = 10; number <= 40 ; number++) {
```

2023-11-05 16:13 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +  if (number % 2 === 1) {
```suggestion
  if (number % 2 !== 0) {
```

2023-11-05 16:13 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +  if (number > 40) {
This check is not necessary. While will stop execution when its condition is evaluated as `true`.

⚠️ FIX: remove final check

2023-11-05 16:13 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_01.js
> +  if (number > 40) {
This check is not necessary. While will stop execution when its condition is evaluated as `true`.

⚠️ FIX: remove final check

2023-11-07 19:18 UTC, MartiCobos99 reviewed
KEEP WORKING ON IT 🤔

2023-11-07 19:18 UTC, MartiCobos99 commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> -const startAt = 10;
FIX! You inicialize the function without value's

NEED WORKS🤔

2023-11-12 12:10 UTC, tictools commented on challenge_03_loops-conditionals/README.md
FIX: remove this file. README should live only at project root level.

2023-11-12 12:12 UTC, tictools requested changes

2023-11-12 12:12 UTC, tictools commented on challenge_03_loops-conditionals/README.md
FIX: remove this file. README should live only at project root level.

2023-11-13 16:50 UTC, MartiCobos99 approved these changes
All in good conditions.

2023-11-13 17:50 UTC, tictools approved these changes

2023-11-13 17:51 UTC, merged